name: Publish Documentation

on:
  workflow_dispatch:

jobs:
  publish-docs:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"
      WYAM_DEPLOY_BRANCH: "gh-pages"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the requested branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ github.event.ref }}
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            2.1.x
            5.0.x
            6.0.x
            7.0.x
      - name: Cache Tools
        uses: actions/cache@v3.3.1
        with:
          path: tools
          key: ${{ runner.os }}-doc-tools-${{ hashFiles('recipe.cake') }}
      - name: Publishing documentaiton
        uses: cake-build/cake-action@v1
        with:
          script-path: recipe.cake
          target: Force-Publish-Documentation
          verbosity: Diagnostic
          cake-version: tool-manifest
